export const images = [
  { image: "https://framerusercontent.com/images/yv3Rrk9zqtaq24U4rDRrApUmFRQ.jpg?scale-down-to=2048",
  title: "Mountains",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/6QtmtICiTmr01Nk0lIdKYXC0fc.jpg?scale-down-to=1024",
  title: "Forest",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/7SZM6o6KIrwEDNf65gPXokbliiM.jpg?scale-down-to=1024",
  title: "Park",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/57VsVVaztJjK6epEym90CCsrpd0.jpg?scale-down-to=1024",
  title: "Countryside",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/FXN7aLDuqfCGBCdTrisNZiQHsDY.jpg?scale-down-to=1024",
  title: "Sea",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/ce7pXAjq2vFWCs3tvuwdhlI0U.jpg?scale-down-to=1024",
  title: "Pastures",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/q6muwHo6ts4QPDmq9btPQ6HT1o.jpg?scale-down-to=1024",
  title: "Sunsets",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/rkKMGw5hSDnBINMWy1DkGES9pgk.jpg?scale-down-to=1024",
  title: "Elks",
  info: "General info about the gallery",
},
  { image: "https://framerusercontent.com/images/urKPENy6bX1ddeZ6ypC1UxGqJ0.jpg?scale-down-to=1024",
  title: "Wildlife",
  info: "General info about the gallery",
},
];